#!name=阿里云盘
#!desc=过滤阿里云盘广告
#!author=RuCu6[https://github.com/RuCu6], 可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Alipan-01.png
#!openUrl=https://apps.apple.com/app/id1494661473
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[Rule]
IP-CIDR,203.107.1.1/24,REJECT,no-resolve

[URL Rewrite]
# 首页活动日历
^https:\/\/member\.alipan\.com\/v2\/activity\/sign_in_luckyBottle - reject-dict
# 首页板块入口
^https:\/\/api\.alipan\.com\/adrive\/v1\/file\/getTopFolders - reject-dict

[Script]
移除阿里云盘广告 = type=http-response, pattern=^https:\/\/(biz)?api\.alipan\.com\/apps\/v\d\/users?\/home\/(?:news|widgets), script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/Alipan/Alipan.js, requires-body=true

移除阿里云盘广告 = type=http-response, pattern=^https:\/\/member\.alipan\.com\/v1\/users\/onboard_list, script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/Alipan/Alipan.js, requires-body=true

[MITM]
hostname = %APPEND% *api.alipan.com, *api.aliyundrive.com, member.alipan.com, member.aliyundrive.com