#!name=百度网盘
#!desc=过滤百度网盘广告，解锁部分SVIP功能。
#!author=RuCu6[https://github.com/RuCu6], chxm1023[https://github.com/chxm1023], WeiGiegie[https://github.com/WeiGiegie], ddgksf2013[https://github.com/ddgksf2013], 可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/BaiduNetDisk.png
#!openUrl=https://apps.apple.com/app/id547166701
#!tag=去广告, 解锁会员
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[Rule]
AND,((DOMAIN-KEYWORD,api100-core-quic-),(DOMAIN-SUFFIX,amemv.com)),REJECT
AND,((DOMAIN-KEYWORD,api100-normal-quic-),(DOMAIN-SUFFIX,amemv.com)),REJECT
AND,((DOMAIN-KEYWORD,api100-normal-quic-aweme-),(DOMAIN-SUFFIX,amemv.com)),REJECT
AND,((DOMAIN-KEYWORD,api100-quic-core-),(DOMAIN-SUFFIX,amemv.com)),REJECT
AND,((DOMAIN-KEYWORD,api100-quic-normal-),(DOMAIN-SUFFIX,amemv.com)),REJECT
AND,((DOMAIN-KEYWORD,frontier100-aweme),(DOMAIN-SUFFIX,amemv.com)),REJECT
AND,((DOMAIN-KEYWORD,ma5-normal-),(DOMAIN-SUFFIX,zijieapi.com)),REJECT
AND,((DOMAIN-KEYWORD,polaris5-normal-),(DOMAIN-SUFFIX,zijieapi.com)),REJECT
AND,((DOMAIN-KEYWORD,webcast100-ws-c-),(DOMAIN-SUFFIX,amemv.com)),REJECT
AND,((DOMAIN-KEYWORD,tnc),(AND,((OR,((DOMAIN-KEYWORD,-bjlgy),(DOMAIN-KEYWORD,-alisc),(DOMAIN-KEYWORD,-aliec),(DOMAIN-KEYWORD,-alisg))),(OR,((DOMAIN-SUFFIX,snssdk.com),(DOMAIN-SUFFIX,isnssdk.com),(DOMAIN-SUFFIX,toutiaoapi.com),(DOMAIN-SUFFIX,bytedance.com),(DOMAIN-SUFFIX,zijieapi.com)))))),REJECT
DOMAIN,frontier-aweme-hl.snssdk.com,REJECT
# DOMAIN, frontier-aweme.snssdk.com, REJECT
DOMAIN,frontier-quic-test.bytedance.com,REJECT
AND,((IP-CIDR,110.249.199.75/32,no-resolve),(DEST-PORT,6443)),REJECT
AND,((IP-CIDR,111.225.147.191/32,no-resolve),(DEST-PORT,6443)),REJECT
AND,((IP-CIDR,111.63.61.101/32,no-resolve),(DEST-PORT,6443)),REJECT
AND,((IP-CIDR,220.243.141.0/32,no-resolve),(DEST-PORT,6443)),REJECT
AND,((DOMAIN-KEYWORD,-ad-),(DOMAIN-SUFFIX,byteimg.com)),REJECT
AND,((DOMAIN-KEYWORD,-ttam-),(DOMAIN-SUFFIX,ibyteimg.com)),REJECT
AND,((DOMAIN-KEYWORD,ssdk-),(DOMAIN-SUFFIX,pangle.io)),REJECT
AND,((DOMAIN-KEYWORD,pangolin),(DOMAIN-SUFFIX,sgsnssdk.com)),REJECT
AND,((DOMAIN-KEYWORD,lf),(DOMAIN-KEYWORD,-short.bytetos.com)),REJECT
AND,((DOMAIN-KEYWORD,v),(DOMAIN-KEYWORD,-be-pack.pglstatp-toutiao.com)),REJECT
AND,((DOMAIN-KEYWORD,sf),(DOMAIN-KEYWORD,-be-pack.pglstatp-toutiao.com)),REJECT
AND,((DOMAIN-KEYWORD,s),(DOMAIN-KEYWORD,-fe-scm.pglstatp-toutiao.com)),REJECT
AND,((DOMAIN-KEYWORD,sf),(DOMAIN-KEYWORD,-ttcdn-tos.pstatp.com)),REJECT
AND,((DOMAIN-KEYWORD,sf),(DOMAIN-KEYWORD,-fe-tos.pglstatp-toutiao.com)),REJECT
AND,((DOMAIN-KEYWORD,sf),(DOMAIN-KEYWORD,-static.i18n-pglstatp.com)),REJECT
AND,((DOMAIN-KEYWORD,if),(DOMAIN-KEYWORD,-cdn-tos.bytescm.com)),REJECT
AND,((DOMAIN-KEYWORD,if),(DOMAIN-KEYWORD,-analytics.bytescm.com)),REJECT
AND,((DOMAIN-KEYWORD,lf),(DOMAIN-KEYWORD,-analytics.bytescm.com)),REJECT
AND,((DOMAIN-KEYWORD,ads),(DOMAIN-KEYWORD,normal),(DOMAIN-SUFFIX,zijieapi.com)),REJECT
AND,((DOMAIN-KEYWORD,api),(DOMAIN-KEYWORD,-access-),(DOMAIN-SUFFIX,pangle.io)),REJECT
AND,((DOMAIN-KEYWORD,api),(DOMAIN-KEYWORD,-log-),(DOMAIN-SUFFIX,pangle.io)),REJECT
AND,((DOMAIN-KEYWORD,api),(DOMAIN-KEYWORD,-dual-event-),(DOMAIN-SUFFIX,pangle.io)),REJECT
AND,((DOMAIN-KEYWORD,api),(DOMAIN-KEYWORD,pangolin),(DOMAIN-SUFFIX,sgsnssdk.com)),REJECT
AND,((DOMAIN-KEYWORD,ads),(DOMAIN-KEYWORD,-normal-lq),(DOMAIN-SUFFIX,zijieapi.com)),REJECT
URL-REGEX,"^http:\/\/p\d+-be-pack-sign\.pglstatp-toutiao\.com\/(ad-app-package|web\.business\.image)\/",REJECT
DOMAIN,mon.zijieapi.com,REJECT
DOMAIN,lf-ad-ies.bytecdn.cn,REJECT
DOMAIN,i.snssdk.com,REJECT
DOMAIN,is.snssdk.com,REJECT
DOMAIN,bds.snssdk.com,REJECT
DOMAIN,dm.bytedance.com,REJECT
DOMAIN,dm.pstatp.com,REJECT
DOMAIN,dm.toutiao.com,REJECT
DOMAIN,log.snssdk.com,REJECT
DOMAIN,s3a.pstatp.com,REJECT
DOMAIN,sdfp.snssdk.com,REJECT
DOMAIN,tosv.boe.byted.org,REJECT
DOMAIN,tosv.byted.org,REJECT
DOMAIN,extlog.snssdk.com,REJECT
DOMAIN,mssdk-bu.bytedance.com,REJECT
DOMAIN,toblog.ctobsnssdk.com,REJECT
DOMAIN,mssdk.volces.com,REJECT
DOMAIN,pangolin.snssdk.com,REJECT
DOMAIN,gromore.pangolin-sdk-toutiao.com,REJECT
DOMAIN,ether-pack.pangolin-sdk-toutiao.com,REJECT
DOMAIN-KEYWORD,-ad-sign.byteimg.com,REJECT
DOMAIN-KEYWORD,api-access.pangolin-sdk-toutiao,REJECT
DOMAIN-KEYWORD,log-api.pangolin-sdk-toutiao,REJECT
DOMAIN-KEYWORD,-ad.byteoversea.com,REJECT
DOMAIN-KEYWORD,video-cn.snssdk.com,REJECT
DOMAIN-KEYWORD,asiad.byteactivity,REJECT
# 百度联盟 - 广告服务商
DOMAIN,mobads.baidu.com,REJECT
DOMAIN,mobads-logs.baidu.com,REJECT
DOMAIN,wn.pos.baidu.com,REJECT
DOMAIN,bgg.baidu.com,REJECT
DOMAIN,als.baidu.com,REJECT
DOMAIN,mobads-pre-config.cdn.bcebos.com,REJECT
DOMAIN,cpro.baidustatic.com,REJECT
DOMAIN,feed-image.baidu.com,REJECT
DOMAIN-SUFFIX,union.baidu.cn,REJECT
DOMAIN-SUFFIX,union.baidu.com,REJECT

[URL Rewrite]
# RuCu6
^https?:\/\/pan\.baidu\.com\/(?:act\/|aipic\/|aisearch\/|api\/getsyscfg\?) - reject-dict
# 拦截HTTPDNS
^https?:\/\/180\.76\.76\.200\/v\d\/resolve - reject
^https?:\/\/180\.76\.76\.112\/v\d\/resolve - reject
# 应用配置
^https:\/\/pan\.baidu\.com\/api\/getconfig - reject-dict
^https:\/\/pan\.baidu\.com\/api\/getsyscfg - reject-dict
# 签到任务配置
^https:\/\/pan\.baidu\.com\/api\/taskscore\/tasklist - reject-dict
# 弹窗配置
^https:\/\/pan\.baidu\.com\/act\/api\/activityentry - reject-dict
# 我的 - 游戏中心
^https:\/\/pan\.baidu\.com\/rest\/2\.0\/membership\/user\?method=gamecenter - reject-dict
# 我的页面 - 其他推广
^https:\/\/pan\.baidu\.com\/act\/v2\/welfare\/list - reject-dict
# 广告配置
^https:\/\/pan\.baidu\.com\/rest\/\d\.\d\/pcs\/adv - reject-dict
# 启动弹窗
^https?:\/\/.*baidu\.com\/rest\/.*\/membership\/proxy\/guide - reject-200
# 设置信息流
^https?:\/\/pan\.baidu\.com\/act\/v\d\/(bchannel|welfare)\/list - reject-200
# 通用广告
^https?:\/\/pan\.baidu\.com\/rest\/.*\/pcs\/ad - reject-200
# 活动推广
^https?:\/\/pan\.baidu\.com\/act\/api\/activityentry - reject-200
# 热搜list
^https:\/\/pan\.baidu\.com\/feed\/hotlist - reject-200
# 活动推广
^https?:\/\/.*zhangyuyidong\.cn\/api\/zysdk - reject-200
# 搜索填词
^https:\/\/pan\.baidu\.com\/queryintent\/queryhint - reject-200
# 金币乐园
^https:\/\/pan\.baidu\.com\/coins\/center\/notice - reject-200

[Script]
# chxm1023
会员权益@chxm1023 = type=http-response, pattern=^https?:\/\/pan\.baidu\.com\/(youai\/(user\/.+\/getminfo|membership\/.+\/adswitch)|(rest\/.+\/membership\/user|act\/.+\/(bchannel|welfare)\/list|api\/usercfg)), script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/bdcloud.js, requires-body=true

# WeiGiegie
会员权益@WeiGiegie = type=http-response, pattern=^https?:\/\/pan\.baidu\.com\.+(rest\/.+\/membership\/user|api\/user\/getinfo|act\/v2\/welfare\/list|api\/taskscore\/tasklist)\?, script-path=https://raw.githubusercontent.com/WeiGiegie/666/main/panda.js, requires-body=true

# RuCu6
百度网盘广告@RuCu6 = type=http-response, pattern=^https:\/\/pan\.baidu\.com\/api\/getsyscfg\?, script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/Baidu/BaiduNetDisk.js, requires-body=true

百度网盘广告@RuCu6 = type=http-response, pattern=^https:\/\/pan\.baidu\.com\/rest\/2\.0\/membership\/user, script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/Baidu/BaiduNetDisk.js, requires-body=true

# 开屏广告
百度网盘广告@ddgksf2013 = type=http-response, pattern=^https?:\/\/pan\.baidu\.com\/api\/getsyscfg, script-path=https://gist.githubusercontent.com/ddgksf2013/f43026707830c7818ee3ba624e383c8d/raw/baiduCloud.adblock.js, requires-body=true

# 广告推广
百度网盘广告@ddgksf2013 = type=http-response, pattern=^https?:\/\/afd\.baidu\.com\/afd\/entry, script-path=https://gist.githubusercontent.com/ddgksf2013/f43026707830c7818ee3ba624e383c8d/raw/baiduCloud.adblock.js, requires-body=true

# 游戏广告
百度网盘广告@ddgksf2013 = type=http-response, pattern=^https:\/\/pan\.baidu\.com\/rest\/.*\/membership\/user\?method=gamecenter, script-path=https://gist.githubusercontent.com/ddgksf2013/f43026707830c7818ee3ba624e383c8d/raw/baiduCloud.adblock.js, requires-body=true

# 首页信息流
百度网盘广告@ddgksf2013 = type=http-response, pattern=^https:\/\/pan\.baidu\.com\/feed\/cardinfos, script-path=https://gist.githubusercontent.com/ddgksf2013/f43026707830c7818ee3ba624e383c8d/raw/baiduCloud.adblock.js, requires-body=true

# 视频倍速
百度网盘视频倍速@ddgksf2013 = type=http-request, pattern=^https:\/\/pan\.baidu\.com\/api\/streaming\?app_id=\d+&type=M3U8_HQ_1080, script-path=https://gist.githubusercontent.com/ddgksf2013/f43026707830c7818ee3ba624e383c8d/raw/baiduCloud.adblock.js

百度网盘视频倍速@ddgksf2013 = type=http-response, pattern=^https:\/\/pan\.baidu\.com\/rest\/.*\/membership\/user, script-path=https://gist.githubusercontent.com/ddgksf2013/f43026707830c7818ee3ba624e383c8d/raw/baiduCloud.adblock.js, requires-body=true

[MITM]
hostname = %APPEND% pan.baidu.com, afd.baidu.com, 180.76.76.200, 180.76.76.112