#!name=Keep
#!desc=过滤Keep广告
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md], ZenmoFeiShi[https://github.com/ZenmoFeiShi]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Keep.png
#!openUrl=https://apps.apple.com/app/id952694580
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[Rule]
# 拦截HTTPDNS
DOMAIN,httpdns.n.netease.com,REJECT
DOMAIN,httpdns.calorietech.com,REJECT
# 拦截广告下发
DOMAIN,hc-ssp.sm.cn,REJECT
# 腾讯
DOMAIN,adsmind.gdtimg.com,REJECT
DOMAIN,adsmind.ugdtimg.com,REJECT
DOMAIN,c2.gdt.qq.com,REJECT
DOMAIN,huatuocode.huatuo.qq.com,REJECT
DOMAIN,info4.video.qq.com,REJECT
DOMAIN,info6.video.qq.com,REJECT
DOMAIN,ios.bugly.qq.com,REJECT
DOMAIN,pro.bugly.qq.com,REJECT
DOMAIN,ios.video.mpush.qq.com,REJECT
# DOMAIN, mazu.m.qq.com, REJECT // 误杀
DOMAIN,us.l.qq.com,REJECT
DOMAIN,mi.gdt.qq.com,REJECT
DOMAIN,otheve.beacon.qq.com,REJECT
DOMAIN,pgdt.gtimg.cn,REJECT
DOMAIN,pgdt.ugdtimg.com,REJECT
# DOMAIN, qzonestyle.gtimg.cn, REJECT // 误杀
DOMAIN,qzs.gdtimg.com,REJECT
DOMAIN,qzs.qq.com,REJECT
DOMAIN,rmonitor.qq.com,REJECT
DOMAIN,sdk.e.qq.com,REJECT
DOMAIN,sdkconfig.video.qq.com,REJECT
DOMAIN,t.gdt.qq.com,REJECT
DOMAIN,tmead.y.qq.com,REJECT
DOMAIN,tmeadbak.y.qq.com,REJECT
DOMAIN,tmeadcomm.y.qq.com,REJECT
DOMAIN,tpns.qq.com,REJECT
DOMAIN,v.gdt.qq.com,REJECT
DOMAIN,v2.gdt.qq.com,REJECT
DOMAIN,win.gdt.qq.com,REJECT
DOMAIN,wup.imtt.qq.com,REJECT
DOMAIN,tpstelemetry.tencent.com,REJECT
DOMAIN,ii.gdt.qq.com,REJECT
DOMAIN-KEYWORD,trace.qq.com,REJECT
DOMAIN-KEYWORD,trace.video.qq.com,REJECT
DOMAIN-SUFFIX,gdt.qq.com,REJECT
DOMAIN-SUFFIX,l.qq.com,REJECT
DOMAIN-SUFFIX,ugdtimg.com,REJECT
IP-CIDR,47.110.187.87/32,REJECT,no-resolve

[Map Local]
# 搜索填充词
^https:\/\/api\.gotokeep\.com\/search\/v\d\/default\/keyword\/list data-type=text data="{}" status-code=200

^https:\/\/api\.gotokeep\.com\/search\/v\d\/(?:hotHashtag|hotCourse|hotword)\/list data-type=text data="{}" status-code=200

# 信息流推广
^https:\/\/api\.gotokeep\.com\/op-engine-webapp\/v\d\/ad\/preload data-type=text data="{}" status-code=200

^https:\/\/kad\.gotokeep\.com\/op-engine-webapp\/v\d\/ad data-type=text data="{}" status-code=200

# 弹窗
^https:\/\/api\.gotokeep\.com\/guide-webapp\/v1\/popup\/getPopUp data-type=text data="{}" status-code=200

# 消息
^https:\/\/api\.gotokeep\.com\/messenger\/v\d\/conversations\/unread data-type=text data="{}" status-code=200

[Script]
body_rewrite_63 = type=http-response, pattern=^https:\/\/api\.gotokeep\.com\/twins\/v4\/feed\/followPage, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=%5B%5B%22json-replace%22%2C%5B%5B%22data%22%2C%7B%7D%5D%5D%5D%5D

body_rewrite_68 = type=http-response, pattern=^https:\/\/api\.gotokeep\.com\/twins\/v4\/feed\/entryDetail, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=%5B%5B%22json-replace%22%2C%5B%5B%22data%22%2C%7B%7D%5D%5D%5D%5D

# 移除我的页面广告
移除我的页面广告 = type=http-response, pattern=^https:\/\/api\.gotokeep\.com\/athena\/v\d\/people\/my, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Keep.js, requires-body=true

# 移除首页活动标签
移除首页活动标签 = type=http-response, pattern=^https:\/\/api\.gotokeep\.com\/config\/v\d\/basic, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Keep.js, requires-body=true

[MITM]
hostname = %APPEND% api.gotokeep.com, kad.gotokeep.com