#!name=Listenify
#!desc=从网易云音乐获取歌词与艺人封面
#!author=Yswag[https://github.com/Yswag]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Listenify.png
#!openUrl=https://apps.apple.com/app/id6475892753
#!tag=功能增强
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[Script]
Lyrics = type=http-request, pattern=^https:\/\/api\.lrc\.cx\/(lyrics|cover), script-path=https://raw.githubusercontent.com/Yswag/for-own-use/main/js/listenify.js, script-update-interval=0

[MITM]
hostname = %APPEND% api.lrc.cx