#!name=夸克
#!desc=过滤夸克广告
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Quark.png
#!openUrl=https://apps.apple.com/app/id1160172628
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[URL Rewrite]
# 小说底部文案广告
^https:\/\/huichuan\.sm\.cn\/nativead$ - reject
^https:\/\/stars\.shuqireader\.com\/kkios\/render\/load\/resource\/appConfig$ - reject-dict

[Script]
# 精简我的页面
精简我的页面 = type=http-response, pattern=^https:\/\/open-cms-api\.quark\.cn\/open-cms, script-path=https://kelee.one/Resource/Script/QuarkBrowser/QuarkBrowser_remove_ads.js, requires-body=true

[MITM]
hostname = %APPEND% huichuan.sm.cn, stars.shuqireader.com, open-cms-api.quark.cn