#!name=铁路12306
#!desc=过滤铁路12306广告
#!author=RuCu6[https://github.com/RuCu6]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Railway12306.png
#!openUrl=https://apps.apple.com/app/id564818797
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[Rule]
# 放行规则
DOMAIN,ad.12306.cn,DIRECT

[Script]
# 移除12306开屏广告
移除12306开屏广告 = type=http-request, pattern=^https:\/\/ad\.12306\.cn\/ad\/ser\/getAdList$, script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/Railway12306/Railway12306.js, requires-body=true

# 移除12306应用内广告
移除12306应用内广告 = type=http-response, pattern=^https:\/\/mobile\.12306\.cn\/otsmobile\/app\/mgs\/mgw\.htm$, script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/MyBlockAds/header.js

[MITM]
hostname = %APPEND% ad.12306.cn, mobile.12306.cn