#!name=Soul
#!desc=Soul全面净化
#!author=ZenmoFeiShi[https://github.com/ZenmoFeiShi], RuCu6[https://github.com/RuCu6], 可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Soul.png
#!openUrl=https://apps.apple.com/app/id1032287195
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[Rule]
# 地理位置 - 影响注册账号时的属地判断
DOMAIN-SUFFIX,soulapp.cn,DIRECT
IP-CIDR,8.210.3.170/32,DIRECT,no-resolve
IP-CIDR,47.75.72.47/32,DIRECT,no-resolve
# 广告下发
DOMAIN,ad-h5-cdn.soulapp.cn,REJECT
DOMAIN,ad-h5-station-cdn.soulapp.cn,REJECT
DOMAIN,ad-r.soulapp.cn,REJECT
DOMAIN,soul-ad.soulapp.cn,REJECT
# 广告域名IP查询
IP-CIDR,47.56.131.76/32,REJECT,no-resolve
IP-CIDR,47.97.215.55/32,REJECT,no-resolve
IP-CIDR,47.99.42.29/32,REJECT,no-resolve
IP-CIDR,47.110.187.87/32,REJECT,no-resolve
IP-CIDR,47.243.147.125/32,REJECT,no-resolve
IP-CIDR,120.27.235.201/32,REJECT,no-resolve
IP-CIDR,121.196.197.147/32,REJECT,no-resolve

[URL Rewrite]
# 开屏广告
^https:\/\/ssp\.soulapp\.cn\/api\/q - reject-dict
^https:\/\/api-chat\.soulapp\.cn\/chat\/quick\/menu\/v2 - reject-dict
^https:\/\/api-chat\.soulapp\.cn\/chat\/guide\/defaultWord - reject-dict
^https:\/\/api-chat\.soulapp\.cn\/chat\/attach\/menu - reject-dict
^https:\/\/api-chat\.soulapp\.cn\/chat\/entrance\/first - reject-dict
^https:\/\/chat-live\.soulapp\.cn\/live\/planet\/recListV2 - reject-200

[Script]
Soul全面净化 = type=http-response, pattern=^https:\/\/(?:api-\w+|gateway-mobile-gray|post)\.soulapp\.cn\/(?:furion\/position\/content|hot\/soul\/rank|mobile\/app\/version\/queryIos|official\/scene\/module|teenager\/config|v2\/post\/gift\/list|v\d\/post\/homepage\/guide\/card), script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=%5B%5B%22json-del%22%2C%5B%22data%22%5D%5D%5D

# 可莉🅥
移除Soul广告 = type=http-response, pattern=^https:\/\/(?:api-\w+|chat-live|post)\.soulapp\.cn\/(?:chat\/limitInfo|chatroom\/chatClassifyRoomList|homepage\/diamond\/position\/info|v2\/post\/recSquare\/subTabs|v6\/planet\/config), script-path=https://kelee.one/Resource/Script/Soul/Soul_remove_ads.js, requires-body=true

# ZenmoFeiShi
Soul全面净化 = type=http-response, pattern=^https:\/\/api-a\.soulapp\.cn\/v2\/post\/gift\/list, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Soul.js, requires-body=true

Soul全面净化 = type=http-response, pattern=^https:\/\/post\.soulapp\.cn\/hot\/soul\/rank, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Soul.js, requires-body=true

Soul全面净化 = type=http-response, pattern=^https:\/\/gateway-mobile-gray\.soulapp\.cn\/mobile\/app\/version\/queryIos, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Soul.js, requires-body=true

Soul全面净化 = type=http-response, pattern=^https:\/\/api-chat\.soulapp\.cn\/chat\/limitInfo, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Soul.js, requires-body=true

Soul全面净化 = type=http-response, pattern=^https:\/\/post\.soulapp\.cn\/v\d\/post\/homepage\/guide\/card, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Soul.js, requires-body=true

Soul全面净化 = type=http-response, pattern=^https:\/\/api-user\.soulapp\.cn\/furion\/position\/content, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Soul.js, requires-body=true

Soul全面净化 = type=http-response, pattern=^https:\/\/api-account\.soulapp\.cn\/teenager\/config, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Soul.js, requires-body=true

Soul全面净化 = type=http-response, pattern=^https:\/\/47\.110\.187\.87\/winterfell\/(?:v2\/)?getIpByDomain, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Soul.js, requires-body=true

Soul全面净化 = type=http-response, pattern=^https:\/\/chat-live\.soulapp\.cn\/chatroom\/chatClassifyRoomList, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Soul.js, requires-body=true

Soul全面净化 = type=http-response, pattern=^https:\/\/api-user\.soulapp\.cn\/v6\/planet\/config, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Soul.js, requires-body=true

Soul全面净化 = type=http-response, pattern=^https:\/\/api-a\.soulapp\.cn\/official\/scene\/module, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Soul.js, requires-body=true

Soul全面净化 = type=http-response, pattern=^https:\/\/post\.soulapp\.cn\/v2\/post\/recSquare\/subTabs, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/Soul.js, requires-body=true

[MITM]
hostname = %APPEND% api*.soulapp.cn, gateway-mobile-gray.soulapp.cn, post.soulapp.cn, ssp.soulapp.cn, chat-live.soulapp.cn, 120.55.55.115, 120.55.62.124, 121.196.203.183, 47.96.20.45, 47.98.54.106, 118.31.112.221, 8.210.3.170, 47.75.72.47, 47.110.187.87