# WhosTV 自动签到
# 适用软件：Quantumult X
# 文件状态：QX 可用
# 用途：QX 用户导入此配置，配置会调用 WhosTVSignin.js 执行抓 Cookie 与签到。

[rewrite_local]
https://whos.tv/api/ url script-request-header https://raw.githubusercontent.com/imzwr214/whos/main/WhosTVSignin.js

[task_local]
30 8 * * * https://raw.githubusercontent.com/imzwr214/whos/main/WhosTVSignin.js, tag=WhosTV 自动签到, enabled=true

[MITM]
hostname = whos.tv
