#!name=银行App
#!desc=过滤部分银行应用广告
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Other-Icon/CNY.png
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[Rule]
# 建设银行
DOMAIN,adv.ccb.com,REJECT
# 内页广告
URL-REGEX,"^http:\/\/mps\.95508\.com\/mps\/icppweb\/images\/mps\/migration\/mpspics\/",REJECT

[URL Rewrite]
# 开屏广告、内页广告
^https:\/\/static\.95508\.com\/icppweb\/images\/modelMaterial\/advertising\/ - reject
# 国寿联盟悬浮组件
^https:\/\/unionsr\.chinalifeonline\.com\.cn\/gslm\/upload\/ - reject-200
# 开屏广告 @jFrecht
^https:\/\/imcs\.citicbank\.com\/cloud\/[a-zA-Z0-9]{32}\.(?:jpg|jpeg|png)\?width=(?:5..|6..|7..|1125|1242|1400|1863|1330|1500|1080)&height=(?:2436|2688|1624|12..|3031|4032|2688|1137|2880|3248|720|23..|1462) - reject
^https:\/\/imcs\.citicbank\.com\/cloud\/([a-fA-F0-9]{32})\.(?:jpg|jpeg|png)\?width=[0-9]{4}&height=[0-9]{4} - reject
# 浦发银行
^https:\/\/lban\.spdb\.com\.cn\/mspmk-web-component\/getAdvertisementList\.ah$ - reject-dict
^https:\/\/lban\.spdb\.com\.cn\/mspmk-web-component\/getAdvList\.ah$ - reject-dict
^https:\/\/lban\.spdb\.com\.cn\/mspmk-web-component\/prefetchAdvList\.ah - reject-dict
# 开屏广告
^https:\/\/s3gw\.cmbimg\.com\/mbappinitads\/ - reject

[MITM]
hostname = %APPEND% static.95508.com, unionsr.chinalifeonline.com.cn, imcs.citicbank.com, lban.spdb.com.cn, s3gw.cmbimg.com