#!name=菜鸟
#!desc=过滤菜鸟广告
#!author=RuCu6[https://github.com/RuCu6], Keywos[https://github.com/Keywos], 可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Cainiao.png
#!openUrl=https://apps.apple.com/app/id951610982
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[Rule]
AND,((URL-REGEX,"^http:\/\/.+\/amdc\/mobileDispatch"),(USER-AGENT,"Cainiao4iPhone*")),REJECT
# DOMAIN, acs4baichuan.m.taobao.com, REJECT
DOMAIN,adsmind.ugdtimg.com,REJECT
DOMAIN,amdc.m.youku.com,REJECT
# DOMAIN, api.sm.cn, REJECT
DOMAIN,apiv4-iyes.youku.com,REJECT
DOMAIN,httpdns.alicdn.com,REJECT
# DOMAIN, cad.youku.com, REJECT
DOMAIN,huichuan-mc.sm.cn,REJECT
DOMAIN,huichuan.sm.cn,REJECT
DOMAIN,iyes.youku.com,REJECT
# DOMAIN, m-vali.cp31.ott.cibntv.net, REJECT
DOMAIN,mc.atm.youku.com,REJECT
# DOMAIN, pre-acs.youku.com, REJECT
DOMAIN,vali-g1.cp31.ott.cibntv.net,REJECT
DOMAIN,vali-ugc.cp31.ott.cibntv.net,REJECT
DOMAIN,yk-ssp.ad.youku.com,REJECT
DOMAIN,ykad-data.youku.com,REJECT

[URL Rewrite]
# 底部发现页 - 角标
^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.app\.home\.tabbar\.marketing\.get\.cn - reject-dict
# 首页 - 好物推荐、商品推广、底部标签页、快递详情页、问卷调查、主页图标
^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.adkeyword\.get\.cn - reject-dict
^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.cncommunity\.my\.station\.query\.cn - reject-dict
^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.(?:batch\.show\.v2|expose\.mreply|index)\.cn - reject-dict
^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.nbopen\.miniapp\.recommend\.cpc\.cn - reject-dict
^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.nbmensa\.research\.researchservice\.(?:acquire|event|close)\.cn - reject-dict
^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.nbpresentation\.(?:homepage\.merge|tabbar\.marketing)\.get\.cn - reject-dict
# 发现页 - 数字角标、裹裹券
^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.com\.cainiao\.cnactivitycenter - reject-dict
^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.com\.cainiao\.cncreditmarket\.hit\.getactivityhit\.cn - reject-dict
^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.com\.cainiao\.longquan\.place\.getpageresourcecontent\.cn - reject-dict
# 支付宝 - 菜鸟小程序
^https:\/\/guide-acs\.m\.taobao\.com\/gw\/mtop\.cainiao\.adx\.flyad\.getad - reject-dict

[Script]
# 我的页面
移除我的页面推广 = type=http-response, pattern=^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.app\.mine\.main\.cn, script-path=https://kelee.one/Resource/Script/Cainiao/Cainiao_remove_ads.js, requires-body=true

# 首页 - 好物推荐、商品推广、底部标签页、快递详情页、问卷调查、主页图标
移除首页推广 = type=http-response, pattern=^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.m?show\.cn, script-path=https://kelee.one/Resource/Script/Cainiao/Cainiao_remove_ads.js, requires-body=true

移除首页推广 = type=http-response, pattern=^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.nbpresentation\.(?:pickup\.empty\.page|protocol\.homepage)\.get\.cn, script-path=https://kelee.one/Resource/Script/Cainiao/Cainiao_remove_ads.js, requires-body=true

# 消息中心
移除消息中心推广 = type=http-response, pattern=^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.nbfriend\.message\.conversation\.list\.cn, script-path=https://kelee.one/Resource/Script/Cainiao/Cainiao_remove_ads.js, requires-body=true

# 支付宝 - 菜鸟小程序
移除菜鸟小程序推广 = type=http-response, pattern=^https:\/\/guide-acs\.m\.taobao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.mshow, script-path=https://kelee.one/Resource/Script/Cainiao/Cainiao_remove_ads.js, requires-body=true

[MITM]
hostname = %APPEND% cn-acs.m.cainiao.com, guide-acs.m.taobao.com