#!name=滴滴出行
#!desc=过滤滴滴出行广告
#!author=ZenmoFeiShi[https://github.com/ZenmoFeiShi], 可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/DiDi.png
#!openUrl=https://apps.apple.com/app/id554499054
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[Rule]
# 拦截HTTPDNS
DOMAIN,hd.xiaojukeji.com,REJECT
# 拦截广告下发
DOMAIN,gwp.xiaojukeji.com,REJECT
AND,((IP-ASN,45090,no-resolve),(DEST-PORT,25641),(PROTOCOL,TCP)),REJECT
AND,((IP-ASN,63646,no-resolve),(DEST-PORT,25641),(PROTOCOL,TCP)),REJECT

[URL Rewrite]
^https:\/\/res\.xiaojukeji\.com\/resapi\/activity\/getMulti\? - reject-dict
^https:\/\/res\.xiaojukeji\.com\/resapi\/activity\/xpget - reject-dict
^https:\/\/ct\.xiaojukeji\.com\/agent\/v3\/feeds - reject-dict
^https:\/\/freight\.xiaojukeji\.com\/gateway - reject-dict
^https:\/\/daijia\.kuaidadi\.com:443\/gateway - reject-dict
^https:\/\/res\.xiaojukeji\.com\/resapi\/activity\/mget - reject-dict
^https:\/\/conf\.diditaxi\.com\.cn\/homepage\/v\d\/other\/fast - reject-dict
^https:\/\/conf\.diditaxi\.com\.cn\/dynamic\/conf - reject-dict
^https:\/\/conf\.diditaxi\.com\.cn\/homepage\/v1\/other\/slow - reject-dict

[MITM]
hostname = %APPEND% common.diditaxi.com.cn, freight.xiaojukeji.com, daijia.kuaidadi.com, 162.14.157.*, ct.xiaojukeji.com, res.xiaojukeji.com, conf.diditaxi.com.cn, api.udache.com, 123.207.209.*, 112.53.55.225, 120.241.142.*, 120.241.143.*, 116.85.*, 139.199.240.84