#!name=粉笔
#!desc=过滤粉笔广告
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Fenbi.png
#!openUrl=https://apps.apple.com/app/id584660358
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[URL Rewrite]
^https:\/\/tiku\.fenbi\.com\/activity\/app\/launcher - reject-dict
^https:\/\/keapi\.fenbi\.com\/app\/iphone\/\w+\/popup - reject-dict
^https:\/\/market-api\.fenbi\.com\/iphone\/v1\/assistant\/info - reject-dict
^https:\/\/market-api\.fenbi\.com\/iphone\/v1\/assistant\/entrance\/show - reject-dict

[MITM]
hostname = %APPEND% keapi.fenbi.com, market-api.fenbi.com, tiku.fenbi.com