#!name=IT之家
#!desc=过滤IT之家广告，自定义移除置顶和轮播图。此插件仅支持8.30及以上版本客户端。
#!author=Keywos[https://github.com/Keywos], 可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/IThome.png
#!openUrl=https://apps.apple.com/app/id570610859
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[URL Rewrite]
^https?:\/\/api\.zuihuimai\.com\/static\/.*\/hongbao - reject
^https?:\/\/dat\.ruanmei\.com\/ithome\/money\/acd\.json$ - reject

[Script]
IT之家去广告 = type=http-response, pattern=^https:\/\/napi\.ithome\.com\/api\/(?:news\/index|topmenu\/getfeeds\?|api\/douyin\/GetLiveInfo), script-path=https://kelee.one/Resource/Script/IThome/IThome_remove_ads.js, requires-body=true, argument=[{removeTopSwitch},{removeBannerSwitch}]

[MITM]
hostname = %APPEND% napi.ithome.com, api.zuihuimai.com, dat.ruanmei.com