#!name=金山文档
#!desc=过滤金山文档广告
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/KDocs.png
#!openUrl=https://apps.apple.com/app/id1398120225
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[Rewrite]
^https:\/\/www\.kdocs\.cn\/kdg\/api\/v1\/cards\/type\/3\?iosVer=\d+\.\d+\.\d+&isGetList=1 - reject-dict

^https:\/\/www\.kdocs\.cn\/kdg\/api\/v1\/cards\/type\/27\?iosVer=\d+\.\d+\.\d+&isGetList=1 - reject-dict

^https:\/\/f-api\.kdocs\.cn\/godfather\/api\/thirdparty\/v1\/viewpager\?showLocal=mobileWebIndex - reject-dict

[MITM]
hostname = %APPEND% www.kdocs.cn, f-api.kdocs.cn