#!name=腾讯视频
#!desc=不负好时光
#!author=RuCu6[https://github.com/RuCu6]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/TencentVideo.png
#!openUrl=https://apps.apple.com/app/id458318329
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-04-17 11:00

[Rule]
OR, ((DOMAIN, pgdt.gtimg.cn), (AND, ((USER-AGENT, "live4iphoneRel*"), (IP-CIDR, 0.0.0.0/0, no-resolve)))), REJECT-DROP
DOMAIN,adsmind.gdtimg.com,REJECT
DOMAIN,info4.video.qq.com,REJECT
DOMAIN,info6.video.qq.com,REJECT
DOMAIN,ios.video.mpush.qq.com,REJECT
DOMAIN,otheve.beacon.qq.com,REJECT
DOMAIN,pgdt.gtimg.cn,REJECT
DOMAIN,tmead.y.qq.com,REJECT
DOMAIN,tmeadbak.y.qq.com,REJECT
DOMAIN,tmeadcomm.y.qq.com,REJECT
DOMAIN,tpns.qq.com,REJECT
DOMAIN-SUFFIX,gdt.qq.com,REJECT
DOMAIN-SUFFIX,l.qq.com,REJECT
DOMAIN-KEYWORD,trace.qq.com,REJECT
DOMAIN-KEYWORD,trace.video.qq.com,REJECT
IP-CIDR,47.110.187.87/32,REJECT,no-resolve
URL-REGEX,"^http:\/\/[\d\.:]*\/?(defaultts\.tc|vmind\.qqvideo\.tc|finderpdd\.video)\.qq\.com\/\w+",REJECT
URL-REGEX,"^http:\/\/apd-vlive\.apdcdn\.tc\.qq\.com\/vmind\.qqvideo\.tc\.qq\.com\/\w+",REJECT
URL-REGEX,"^http:\/\/apd-\w+\.v\.smtcdns\.com\/(defaultts|omts|vmind\.qqvideo)\.tc\.qq\.com\/\w+",REJECT

[URL Rewrite]
^http:\/\/[\d\.:]*\/?(defaultts\.tc|vmind\.qqvideo\.tc|finderpdd\.video)\.qq\.com\/\w+ - reject
^http:\/\/apd-vlive\.apdcdn\.tc\.qq\.com\/vmind\.qqvideo\.tc\.qq\.com\/\w+ - reject
^http:\/\/apd-\w+\.v\.smtcdns\.com\/(defaultts|omts|vmind\.qqvideo)\.tc\.qq\.com\/\w+ - reject
^https?:\/\/vv\.video\.qq\.com\/(diff|get)vmind - reject-dict

[Script]
腾讯视频 = type=http-request, pattern=^https?:\/\/vv\.video\.qq\.com\/getvinfo, script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/CommonScript/replace-body.js, requires-body=true, argument="&sppreviewtype=\d(.*)&spsrt=\d->&sppreviewtype=0$1&spsrt=0"

[MITM]
hostname = %APPEND% vv.video.qq.com